### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by unl1002** [QWTforGithub/CDSegNet#1]
hello, Thank you for your work! When will the code be released?

**Comment by QWTforGithub** [comment]
Thank you for your interest in our work. We have already sorted out the code. But I am currently applying for some funds, which will take a few days. This usually takes no more than 10 days.

**Comment by unl1002** [comment]
Thank you, it seems that you have approved CVPR2025? congratulations!!

**Comment by QWTforGithub** [comment]
Thank you. Yes, I have received an email notifying me that CVPR has accepted this paper on OpenReview. If nothing goes wrong, our paper should be published smoothly.

**Comment by unl1002** [comment]
Best wishes for you!

**Comment by QWTforGithub** [comment]
Thank you! Same to you!

**Comment by QWTforGithub** [comment]
Hello, the code has been uploaded and you can download it. Maybe there are some problems with the code I just uploaded. If you encounter any problems when using the code, please contact me and I will fix it as soon as possible. Thank you.

**Comment by unl1002** [comment]
Thank you for uploading the code! I will check it, and if I encounter any issues, I will let you know. Thank you for your efforts in maintaining and updating the code.

**Comment by unl1002** [comment]
Hello, I downloaded  the processed ScanNet dataset according to the README.md file. After running the script`python tools/train_CDSegNet_ScanNet.py`, an error occurred
``` 
Traceback (most recent call last):
  File "/home/zdr/workspace/code/CDSegNet/tools/train_CDSegNet_ScanNet.py", line 82, in <module>
    main()
  File "/home/zdr/workspace/code/CDSegNet/tools/train_CDSegNet_ScanNet.py", line 69, in main
    launch(
  File "/home/zdr/workspace/code/CDSegNet/pointcept/engines/launch.py", line 74, in launch
    mp.spawn(
  File "/home/zdr/anaconda3/envs/cnf/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/zdr/anaconda3/envs/cnf/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/home/zdr/anaconda3/envs/cnf/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/scheduler.py", line 128, in __init__
    super().__init__(
  File "/home/zdr/anaconda3/envs/cnf/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 1582, in __init__
    raise ValueError(f"Expected positive integer total_steps, but got {total_steps}")
ValueError: Expected positive integer total_steps, but got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/registry.py", line 53, in build_from_cfg
    return obj_cls(**args)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/engines/train.py", line 142, in __init__
    self.scheduler = self.build_scheduler()
  File "/home/zdr/workspace/code/CDSegNet/pointcept/engines/train.py", line 351, in build_scheduler
    return build_scheduler(self.cfg.scheduler, self.optimizer)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/scheduler.py", line 147, in build_scheduler
    return SCHEDULERS.build(cfg=cfg)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
ValueError: OneCycleLR: Expected positive integer total_steps, but got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zdr/anaconda3/envs/cnf/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/engines/launch.py", line 137, in _distributed_worker
    main_func(*cfg)
  File "/home/zdr/workspace/code/CDSegNet/tools/train_CDSegNet_ScanNet.py", line 26, in main_worker
    trainer = TRAINERS.build(dict(type=cfg.train.type, cfg=cfg))
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/registry.py", line 214, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/zdr/workspace/code/CDSegNet/pointcept/utils/registry.py", line 56, in build_from_cfg
    raise type(e)(f"{obj_cls.__name__}: {e}")
ValueError: Trainer: OneCycleLR: Expected positive integer total_steps, but got 0
```

**Comment by QWTforGithub** [comment]
Hi, this is probably because the correct dataset path is not set. I have updated the readme today. 
Configure the dataset path:
    a. CDSegNet-main/configs/scannet/CDSegNet.py
    b. data_root = "Your scannet path" For example,  data_root = "/../CDSegNet-main/data/scannet"

**Comment by unl1002** [comment]
I modified the path of the dataset, but the error still occurred.

![Image](https://github.com/user-attachments/assets/2ff378e2-33a4-4e89-8a9f-af2aff17eb15)

**Comment by unl1002** [comment]
I have modified the path of the dataset, but the error still occurred.

![Image](https://github.com/user-attachments/assets/2c12e0fd-1408-48a2-b132-f66ca131337f)

**Comment by QWTforGithub** [comment]
你好，把路径改成绝对路径试试呢

**Comment by QWTforGithub** [comment]
![Image](https://github.com/user-attachments/assets/82739660-3ca6-4302-b719-c77eddaf6402)这是我的路径设置

**Comment by unl1002** [comment]
> I have modified the path of the dataset, but the error still occurred.
> 
> ![Image](https://github.com/user-attachments/assets/2c12e0fd-1408-48a2-b132-f66ca131337f)

这个是绝对路径的，相对路径我也尝试了，也还是会报这个问题，好奇怪

**Comment by QWTforGithub** [comment]
这应该就是路径问题，因为我把路径设置成错误，也是这种错误。

![Image](https://github.com/user-attachments/assets/74f23e12-9541-44f3-a8a9-72cfc89e7231)
你的scannet文件夹中有数据吗

**Comment by QWTforGithub** [comment]
或者，你将scannet移动到这样的路径呢，/home/zdr/scannet，然后，使用这个路径

**Comment by unl1002** [comment]
有的，https://huggingface.co/datasets/Pointcept/scannet-compressed
![Image](https://github.com/user-attachments/assets/34df7098-075c-4df2-9ab6-a7790ec3c6e8)

**Comment by QWTforGithub** [comment]
你的路径好像不对吧，ctrl+L，看一下绝对路径

![Image](https://github.com/user-attachments/assets/ae19e045-d666-41a9-8d92-acc28e5cbacd)

**Comment by unl1002** [comment]
![Image](https://github.com/user-attachments/assets/65e7f1ea-5511-4521-8d98-5552ce926038)

**Comment by QWTforGithub** [comment]
咦，你的文件怎么不是.pth结尾呢，这不是处理好的scannet把

![Image](https://github.com/user-attachments/assets/d58cc6cb-6b24-4cbb-964b-7c118de646e6)

**Comment by QWTforGithub** [comment]
是在这里下载的吗，https://huggingface.co/datasets/Pointcept/scannet-compressed/tree/main

**Comment by unl1002** [comment]
> 是在这里下载的吗，https://huggingface.co/datasets/Pointcept/scannet-compressed/tree/main

对

**Comment by QWTforGithub** [comment]
哦，我想起来了，PTv3的作者把pth的文件变成.npy的形式了。今晚我会上传pth到百度网盘处理好的pth文件。明天可以下载了。你也可以自己处理文件：

![Image](https://github.com/user-attachments/assets/00d08beb-c3cd-4367-95d9-4be6f8ca17ae)
将npy合成一个pth文件。写个循环就可以了。

**Comment by QWTforGithub** [comment]
今晚，我会在代码里增加一个npy合成pth的脚本，不好意思啊，忘记了这件事~

**Comment by unl1002** [comment]
没关系的，感谢你的及时回复~

**Comment by QWTforGithub** [comment]
你好，我想我应该是修复了这个问题。修改了 [scannet.py](https://github.com/QWTforGithub/CDSegNet/blob/main/pointcept/datasets/scannet.py) ，使得代码能够读取.pth以及.npy。明天，我会测试一下使用.npy文件的结果。大概率不会有什么变化。nuscenes数据集是统一格式的，不要调整。你可以重新下载代码，运行试一下。

**Comment by unl1002** [comment]
感谢！我已经成功运行了代码

**Comment by QWTforGithub** [comment]
我用.npy文件测试的结果没有什么变化。

![Image](https://github.com/user-attachments/assets/66c3628b-209a-4af3-b9d7-0eb54ad99ae8)
如果，你要重新训练的话，注意看一下training tricks。那样能够得到最优的结果。

**Comment by unl1002** [comment]
ok
